name: shoppy3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  #FIREBASE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  google_sign_in: ^6.2.1
  image_picker: ^0.8.5+3
  file_picker: ^8.1.3


  #ICONOS
  flutter_svg: ^2.0.10+1

  #PERSONALIZACION
  liquid_pull_to_refresh: ^3.0.1
  animate_text: ^1.0.0
  animate_do: ^2.0.0
  circular_countdown_timer: ^0.2.4
  confetti: ^0.8.0

  #ADMIN
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0
  rename_app: ^1.5.0
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/


